### ISSUE TITLE
Getting stdout maxBuffer exceeded error

### ISSUE THREAD

**Issue by roger-beathard** [mscgenjs/mscgenjs-cli#14]
I am getting "stdout maxBuffer exceeded" error when processing this file.  I have narrow this issue to the execFile call in action.js script.  This seems to be caused by the stdout buffer being too small.  

If I increase the maxBuffer to 1 meg then the script will generate the attached svg file.
         childProcess.execFile(binPath, args,{maxBuffer:1000000}, (pErr, pStdout/\* , pStderr*/) => {

Some of the websites seem to indicate that it is better to handle this via a spawn, however I do not know if this function can be rewritten using spawn.

[ts.xu.gz](https://github.com/sverweij/mscgenjs-cli/files/365183/ts.xu.gz)

**Comment by sverweij** [comment]
@rbeathar thanks for this issue! I'll try to look into it this weekend.

**Comment by sverweij** [comment]
@rbeathar 69fccf4 implements your fix with a buffer size of 1Mb, which alleviates the problem. I've looked in to your suggestion to use `spawn` - and that indeed looks like a more permanent fix. I'll release version 1.4.3 this weekend. It will include the `spawn` fix if I'm ready in time, but the workaround if not.

**Comment by roger-beathard** [comment]
No rush for me, the work around works for me. I was thinking I was going to have to resort to using plantuml. I like the look of the rendering from mscgen-js and the finer controls for colors. I am glad there is a work around.

Thanks for the support.

**Comment by sverweij** [comment]
Version [1.4.3](https://github.com/sverweij/mscgenjs-cli/releases/tag/1.4.3) includes the `spawn` fix - that was a good suggestion! It should be on npm by now (a new version was due anyway).

And thanks for your kind words :-)

**Comment by sverweij** [comment]
(With the fix of the 15th I consider this issue fixed - closing)
