### ISSUE TITLE
configuring mscgen js.cli for internal network

### ISSUE THREAD

**Issue by simard57** [mscgenjs/mscgenjs-cli#18]
forgive me if this is a naive question - I am not a developer.
I would like to create mscgen diagrams through a CLI interface on an internal network without any internet connection. I loaded the mscgen_js program on internal machine and can use it interactively.

do I need to configure the cli to use that internal server - it is not apparent to me where to do that.

**Comment by sverweij** [comment]
Hi @simard57 

the cli is completely standalone - it doesn't need configuration nor does it need a connection to any server, on the internet or otherwise. Just install & run :-)

**Comment by simard57** [comment]
Ah very good.

I thought it used Phantom JS to remote into a server.

 

 

 

Don Simard

Johns Hopkins University Applied Physics Lab

(443) 778-8955 (Office)

(443) 691-0542 (Cell)

 <mailto:Donald.simard@gccs.jhuapl.contractor.navsea.navy.smil.mil> Donald.simard@gccs.jhuapl.contractor.navsea.navy.smil.mil (SIPR)

 <mailto:Donald.Simard.ctr@mail.mil> Donald.Simard.ctr@mail.mil (NIPR)

 <mailto:Donald.Simard@jhuapl.edu> Donald.Simard@jhuapl.edu (Work)

 <mailto:donsimard@verizon.net> donsimard@verizon.net (Home)

**Comment by simard57** [comment]
Thank you for the quick reply - 
is there a pre-built Windows executable?

**Comment by sverweij** [comment]
- At the moment there is no pre-built windows executable (and at the moment I don't know of any solution that can package a nodejs application as such either)
- mscgenjs-cli's functionality is limited on windows (issue #5) - at least as far as I could test it (windows 7 under cmd, powershell and even baboon) . It'll probably be resolved when mscgenjs-cli is migrated off of phantomjs and onto chrome headless, which is a [planned feature](https://github.com/orgs/mscgenjs/projects/1#card-4113090).

What is the use case you have for the cli?

**Comment by simard57** [comment]
I am writing a program that creates mscgen js scripts and I wanted to create sequence diagrams programmatically (shell mscgen script) instead of using the interactive page ...

**Comment by sverweij** [comment]
That's indeed exactly what I wrote mscgenjs-cli for...

Partly triggered by your question I've been working the past day on replacing phantoms (PR #19) with chrome headless. First tests confirm what I hoped:
- mscgenjs-cli finally works on windows too
- it's (at least) twice as fast as the previous version

It'll be released on `npm` today or tomorrow. If you don't want to wait for that - a _beta_ version is already on it so if you want to try it you can install it with `npm install --global mscgenjs-cli@2.0.0-beta-2` (assuming you've got nodejs on your machine).

**Comment by sverweij** [comment]
... and published: https://www.npmjs.com/package/mscgenjs-cli

a regular `npm install --global mscgenjs-cli` will work from now on to get the latest.

**Comment by simard57** [comment]
Is there a Windows equivalent to npm?

**Comment by sverweij** [comment]
Hi, npm is the package manager for nodejs - and there definitely is a windows version of it: https://nodejs.org/en/ . If you install that (take the LTS version) and go to the command line, you can consecutively

```sh
npm install --global mscgenjs-cli
```

and when that is done you can use mscgenjs as if were a 'normal' windows executable:

```sh
mscgenjs mycoolchart.msc
```

**Comment by simard57** [comment]
Thanks – got it!
Much appreciated.

**Comment by simard57** [comment]
Great – thank you!
I am up and running now.
Thrilled!

**Comment by sverweij** [comment]
Cool! Enjoy it (and let me know if you bump into something you want different or improved :-) )

**Comment by simard57** [comment]
I want better VBA expertise --- but that is on me, not you
